void tileMap(){

int pointx=1;
int pointy=1;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/stone.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    spriteRender("gfx/grass.png", 1, 1, 64*pointx+scrollX, 64*pointy+scrollY);
    pointx++;

    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
    pointy++;
    pointx=1;
}
